### PR TITLE
Save site template ID when creating a new group site

### PR DESCRIPTION
**Pull request by Mamaduka**
This can be used to generate stats about site template usage in the future.

### CODE REVIEW

**Comment by boonebgorges** [comment]
I think this will mean bumping the minimum WP version to 5.1.0. This is OK with me, but we must be sure to do it. @Mamaduka Do you have push access to commons-in-a-box to make the change? (see the header at loader.php)

**Comment by Mamaduka** [comment]
@boonebgorges I think I have.

CBOX uses a custom header property for a minimum WP core version. Should I update that or add new `Requires at least:`?

**Comment by boonebgorges** [comment]
Do both. I think that the custom header is for compatibility with our internal "requirements" library, which predates the 'Requires at least' header in core.

**Comment by Mamaduka** [comment]
Done.

**Comment by boonebgorges** [comment]
Thanks!

**Pull request merged**
